#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dsctl-detect-media-removal" ]; then
	update-rc.d dsctl-detect-media-removal defaults >/dev/null
	invoke-rc.d dsctl-detect-media-removal start || exit $?
fi
# End automatically added section
