#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dsctl-detect-media-removal" ]; then
	invoke-rc.d dsctl-detect-media-removal stop || exit $?
fi
# End automatically added section
